version: "3.1"

services:
    sqlserver:
        container_name: caieradev
        image: "mcr.microsoft.com/azure-sql-edge"
        restart: always
        ports:
            - "1433:1433"
        volumes:
            - "./.data/mssql:/var/opt/mssql"
        environment:
            SA_PASSWORD: "CaioMiguel11!"
            ACCEPT_EULA: "Y"
